cc_binary(
    name = "vec_math",
    srcs = ["vec_math.c"],
    deps = [
        "//lib/misc",
        "//src:DoubleVector",
    ],
)

cc_binary(
    name = "vec_column",
    srcs = ["vec_column.c"],
    deps = [
        "//lib/misc",
        "//src:DoubleVector",
    ],
)
