cc_test(
    name = "test_DoubleMatrix",
    timeout="short",
    srcs = ["test_DoubleMatrix.c"],
    deps = [
        "//lib/misc",
        "//src:DoubleMatrix",
        "@Unity",
    ],
)

cc_test(
    name = "test_DoubleVector",
    timeout="short",
    srcs = ["test_DoubleVector.c"],
    deps = [
        "//lib/misc",
        "//src:DoubleVector",
        "@Unity",
    ],
)
