cc_binary(
    name = "example_matrix",
    srcs = ["example_matrix.c"],
    deps = [
        "//lib/misc",
        "//src:dm_io",
        "//src:dm_math",
        "//src:dm_matrix",
    ],
)

cc_binary(
    name = "example",
    srcs = ["example.c"],
    deps = [
        "//lib/misc",
        "//src:dm_io",
        "//src:dm_math",
        "//src:dm_matrix",
    ],
)

cc_binary(
    name = "example_vector",
    srcs = ["example_vector.c"],
    deps = [
        "//lib/misc",
        "//src:dm_io",
        "//src:dm_math",
        "//src:dm_matrix",
    ],
)
