cc_binary(
    name = "example_matrix",
    srcs = ["example_matrix.c"],
    deps = [
        "//lib/misc",
        "//src:DoubleMatrix",
        "//src:DoubleVector",
    ],
)

cc_binary(
    name = "example_vector",
    srcs = ["example_vector.c"],
    deps = [
        "//lib/misc",
        "//src:DoubleVector",
    ],
)
